spring:
    kafka:
        bootstrap-servers: 127.0.0.1:9092
#        consumer:
#            group-id: payment
#            auto-offset-reset: earliest
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#        producer:
#            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    datasource:
        url: jdbc:h2:mem:kafka-demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE
        driver-class-name: org.h2.Driver
        username: root
        password: root
    h2.console:
        enabled: true
        path: /h2