server.port: 8090
spring:
    kafka:
        bootstrap-servers: 3.123.208.250:9092, 3.125.135.101:9092, 52.58.100.30:9092
#        consumer:
#            group-id: payment
#            auto-offset-reset: earliest
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#        producer:
#            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    datasource:
        url: jdbc:mysql://kafka-demo.cm2glzt6ldw4.eu-central-1.rds.amazonaws.com:3306/kafka_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: root
        password: qwerty2019
        driverClassName: com.mysql.jdbc.Driver
        poolName: kafka-demo-api-dbconnectionpool
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: update
        open-in-view: false
